// Generated by Wrangler on Sun Aug 18 2024 00:46:39 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	RIKI_API_BASE_URL: string;
	RIKI_INTERNAL_API_KEY: string;
}
